/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aidamujcinovicrs2.Konekcija;
import aidamujcinovicrs2.Vozac;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author User
 */
public class UnosVozaca extends javax.swing.JFrame {

    /**
     * Creates new form UnosVozaca
     */
    public UnosVozaca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIme = new javax.swing.JLabel();
        lblPrezime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIDVozilo = new javax.swing.JLabel();
        lblGreska = new javax.swing.JLabel();
        brnUnesiVozaca = new javax.swing.JButton();
        btnVratiSe = new javax.swing.JButton();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        izborGodiste = new javax.swing.JComboBox<>();
        izborVozilo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIme.setText("Ime");

        lblPrezime.setText("Prezime");

        jLabel3.setText("Godiste");

        lblIDVozilo.setText("ID Vozilo");

        brnUnesiVozaca.setText("UNESI");
        brnUnesiVozaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnUnesiVozacaActionPerformed(evt);
            }
        });

        btnVratiSe.setText("NAZAD");
        btnVratiSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVratiSeActionPerformed(evt);
            }
        });

        String godista[]=new String[50];
        int j=0;
        for(int i=1950;i<2000;i++){
            godista[j]=String.valueOf(i);
            j++;
        }
        izborGodiste.setModel(new javax.swing.DefaultComboBoxModel<>(godista));
        izborGodiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izborGodisteActionPerformed(evt);
            }
        });

        String vozila []=null;
        try{
            Konekcija konekcija=new Konekcija();
            ResultSet ct=konekcija.getRowCount();
            ct.next();
            int count=ct.getInt(1);
            vozila=new String[count];
            vozila[0]="Izaberite id vozila";
            ResultSet voziloList=konekcija.ispisiVozila();
            int k;
            int i=0;
            while(voziloList.next()){
                k=voziloList.getInt("id");
                vozila[i]=String.valueOf(k);
                i++;
            }
        }catch(SQLException e){
            System.err.println(e);

        }
        izborVozilo.setModel(new javax.swing.DefaultComboBoxModel<>(vozila));
        izborVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izborVoziloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrezime)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(58, 58, 58)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrezime)
                            .addComponent(izborGodiste, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(btnVratiSe)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brnUnesiVozaca))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblGreska, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblIDVozilo, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(51, 51, 51)
                            .addComponent(izborVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrezime)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(izborGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDVozilo)
                    .addComponent(izborVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGreska)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVratiSe)
                        .addComponent(brnUnesiVozaca)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnUnesiVozacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnUnesiVozacaActionPerformed
        String ime=txtIme.getText();
        String prezime=txtPrezime.getText();
        
        String godiste=(String) izborGodiste.getSelectedItem();
        String idVozilo=(String) izborVozilo.getSelectedItem();
        
       
        Vozac vozac;
        vozac = new Vozac(ime, prezime,Integer.parseInt(godiste),Integer.parseInt(idVozilo));

        if(ime.isEmpty() || prezime.isEmpty() ||godiste.isEmpty()|| idVozilo.isEmpty()){
            lblGreska.setText("Molimo vas ispunite sva polja");
        }
        try{
            Konekcija kon=new Konekcija();
            kon.unosVozaca(vozac);
              this.dispose();
                Pocetna is=new Pocetna();
                
                is.setVisible(true);
        }catch(SQLException e){
            System.out.println(e);
        }    
// TODO add your handling code here:
    }//GEN-LAST:event_brnUnesiVozacaActionPerformed

    private void btnVratiSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVratiSeActionPerformed
        this.dispose();
        Pocetna pocetna=new Pocetna();
        pocetna.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btnVratiSeActionPerformed

    private void izborGodisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izborGodisteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_izborGodisteActionPerformed

    private void izborVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izborVoziloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_izborVoziloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosVozaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosVozaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosVozaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosVozaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosVozaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnUnesiVozaca;
    private javax.swing.JButton btnVratiSe;
    private javax.swing.JComboBox<String> izborGodiste;
    private javax.swing.JComboBox<String> izborVozilo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblGreska;
    private javax.swing.JLabel lblIDVozilo;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
